# travis-ci.org definition for oct2py build

# After changing this file, check it on:
#   http://lint.travis-ci.org/

# http://conda.pydata.org/docs/travis.html
language: python
dist: trusty
sudo: required
cache:
  apt: true
  pip: true

env:
    - CONDA="python=2.7 numpy>=1.11 scipy=0.17.0" KERNEL="python2"
    - CONDA="python=3.5 scipy" KERNEL="python3"
    - CONDA="python=3.6 scipy" KERNEL="python3"

before_install:
  - sudo apt-get install -qq octave liboctave-dev;
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - travis_retry conda create -n test $CONDA jupyter pytest pip nose
  - source activate test
  - travis_retry pip install codecov

install:
  - export PYTHONWARNINGS=all
  - pip install -e .[test]

script:
    # run coverage on py3.5, regular on others
  - if [[ $CONDA == python=3.5* ]]; then
      make cover;
    else
      make test;
    fi
  - make docs

notifications:
  email:
    - steven.silvester@ieee.org

after_success:
    - codecov
